import {createRouter,createWebHistory} from 'vue-router';
const router = createRouter({
    history:createWebHistory(),
    routes:[
        {
            name:"home",
            path:"/home",
            component:()=>import("../views/HomePage.vue")
        },
        {
            name:"test",
            path:"/test",
            component:()=>import("../views/TestPage.vue")
        },
        {
            name:"login",
            path:"/login",
            component:()=>import("../views/LoginPage.vue")
        },
        {
            name:"queryuser",
            path:"/queryuser",
            component:()=>import("../views/QueryUserPage.vue")
        },
        {
            name:"queryplan",
            path:"/queryplan",
            component:()=>import("../views/RecruitmentPlanPage.vue")
        },
        {
            name:"adduser",
            path:"/adduser",
            component:()=>import("../views/AddUserPage.vue")
        },
        {
            name:"addplan",
            path:"/addplan",
            component:()=>import("../views/AddPlanPage.vue")
        },
        {
            name:"addtrain",
            path:"/addtrain",
            component:()=>import("../views/AddTrainPage.vue")
        },
        {
            name:"querytrain",
            path:"/querytrain",
            component:()=>import("../views/QueryTrainPage.vue")
        },
        {
            name:"querysalary",
            path:"/querysalary",
            component:()=>import("../views/QuerySalaryPage.vue")
        },
        {
            name:"querytrainusers",
            path:"/querytrainusers",
            component:()=>import("../views/QueryTrainUsersPage.vue")
        },
        {
            name:"querycontract",
            path:"/querycontract",
            component:()=>import("../views/QueryContractPage.vue")
        },
        {
            name:"userinf",
            path:"/userinf",
            component:()=>import("../views/UserInfPage.vue")
        }
    ]
})
export default router